environment:
  global:
    MSYSTEM: "MINGW64"
    LMDB_VERSION: "0.9.18"

version: 0.0.0.{build}

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syuu mingw-w64-x86_64-qt5 mingw-w64-x86_64-lmdb"

build_script:
  - C:\msys64\usr\bin\bash.exe -lc "cd $APPVEYOR_BUILD_FOLDER; cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -H. -Bbuild -G 'MSYS Makefiles'; make -C build -j2"

after_build:
  - ps: md nachat
  - ps: Copy-Item "build/src/nachat.exe" -Destination "nachat/"
  - C:\msys64\usr\bin\bash.exe -lc "cp `ldd $APPVEYOR_BUILD_FOLDER/nachat/nachat.exe |cut -d' ' -f3 |grep /mingw64/bin/` $APPVEYOR_BUILD_FOLDER/nachat/"
  - C:\msys64\usr\bin\bash.exe -lc "windeployqt.exe --release --no-libraries $APPVEYOR_BUILD_FOLDER/nachat/nachat.exe"
  - 7z a nachat.zip nachat/
  - 7z a nachat.exe.zip ./nachat/nachat.exe

artifacts:
  - path: nachat.zip
  - path: nachat.exe.zip
